language: node_js
node_js:
- "0.10"

before_script:
- mysql -e 'create database test_site;'
- echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
- mysql -hlocalhost -P8889 -uroot -p'root' test_site < test/setup/setup_mysql.sql

script:
- npm link
- npm test